### ISSUE TITLE
SQLexception whenever the plugin isn't used for hours. 

### ISSUE THREAD

**Issue by Robotv2** [WiIIiam278/HuskBungeeRTP#2]
Well the issue is in the title, when no one used the rtp command or plugin for hours. A SQLexception is throw.
Complete stacktrace: https://pastebin.com/MvAyGEn2

**Comment by WiIIiam278** [comment]
Closed in https://github.com/WiIIiam278/HuskBungeeRTP/commit/3bb1ea4afe3272d7655795b25563985f8c18cddf
